### PR TITLE
More removal of d

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by atsb** [comment]
Did you manage to find where htoi was defined?  Because I got undefined errors when I tried to do that when I replaced the memset stuff.  Seems htoi isn't in modern windows at all and there is no alternative.

**Comment by Wolf3s** [comment]
> Did you manage to find where htoi was defined? Because I got undefined errors when I tried to do that when I replaced the memset stuff. Seems htoi isn't in modern windows at all and there is no alternative.

It was a created function by kaiser i will look for him to ask what to do or go to the hard way

**Comment by atsb** [comment]
I merged this in to test it.  After fixing a few things, we really have to keep these d functions around.  Nothing gets loaded at all, no barrels, no enemies, no mobj's.  We can't do that to the project, I'll have to revert.

**Comment by Wolf3s** [comment]
> I merged this in to test it. After fixing a few things, we really have to keep these d functions around. Nothing gets loaded at all, no barrels, no enemies, no mobj's. We can't do that to the project, I'll have to revert.

Yes, revert it or try to add the htoi and some misc functions

**Pull request merged**
