### PR TITLE
Updates on readme

### PR DESCRIPTION
**Pull request by Wolf3s**
- Removed SDL_net
- Added or instead of the because it's optional

### CODE REVIEW

**Comment by thekovic** [comment]
Cross Platform only applies to Linux so I don't see the need for the header change. Also, there's a typo in your current draft

**Comment by atsb** [comment]
Yeah I see the typo :) 'Plataform'.  Once I get a chance, I'll probably add some macOS specific stuff too.

**Comment by Wolf3s** [comment]
> Cross Platform only applies to Linux so I don't see the need for the header change. Also, there's a typo in your current draft



> Yeah I see the typo :) 'Plataform'. Once I get a chance, I'll probably add some macOS specific stuff too.

Oh

**Comment by atsb** [comment]
Lovely now :)

**Comment by Wolf3s** [comment]
> > Cross Platform only applies to Linux so I don't see the need for the header change. Also, there's a typo in your current draft
> 
> > Yeah I see the typo :) 'Plataform'. Once I get a chance, I'll probably add some macOS specific stuff too.
> 
> Oh

Fixed the typo.

**Pull request merged**
