### PR TITLE
remove dgl since me and kaiser on discord found this guy nosense/useless at all

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by atsb** [comment]
*praying for this virus to be eradicated* 🗡️

**Comment by Wolf3s** [comment]
Update: 90% was removed however, if i remove the last thing it broke.

**Comment by Wolf3s** [comment]
@atsb

**Comment by atsb** [comment]
Did you manage to do it?

**Comment by Wolf3s** [comment]
> Did you manage to do it?

Yes, it was hard

**Comment by atsb** [comment]
Awesome!  I’ll compile this and test it before merging just to make sure it all works nicely

**Comment by Wolf3s** [comment]
> Awesome! I’ll compile this and test it before merging just to make sure it all works nicely

Ok do your test, besides the psvita was fixed also

**Comment by atsb** [comment]
Really!  Awesome stuff.  Is it ok to send me the vita binary on discord?  I’ve tried using the sdk but it either hates me or Im doing something stupid :D

**Comment by Wolf3s** [comment]
> Really! Awesome stuff. Is it ok to send me the vita binary on discord? I’ve tried using the sdk but it either hates me or Im doing something stupid :D

Yes, i will send it

**Comment by atsb** [comment]
is this line in st_stuff meant to be` #if defined(_WIN32) && defined(USE_XINPUT) || defined(VITA) // XINPUT` because if it is !defined VITA then it is there for Linux and Mac too ;)

**Comment by Wolf3s** [comment]
> is this line in st_stuff meant to be` #if defined(_WIN32) && defined(USE_XINPUT) || defined(VITA) // XINPUT` because if it is !defined VITA then it is there for Linux and Mac too ;)

Crap

**Comment by atsb** [comment]
works on windows, merging

**Pull request merged**
