### PR TITLE
SDL3 version

### PR DESCRIPTION
**Pull request by atsb**
This is the future of EX+ and will be merged once SDL3 becomes stable.  There won't be a release until that happens.  This will be merged Day 1 and will be the first Doom source port converted to it.

### CODE REVIEW

**Comment by Wolf3s** [comment]
> This is the future of EX+ and will be merged once SDL3 becomes stable. I won't be a release until that happens. This will be merged Day 1 and will be the first Doom source port converted to it.

You prefer when SDL3 is released?

**Comment by bubbleguuum** [comment]
@atsb 

Glad you are picking up on EX+ again !
One area of improvement I'd like is the sound subsystem, to make it more in line with the remaster (which has way superior audio quality), if that's possible. And the ability to use its audio assets (rather than the .sf2).

**Comment by bubbleguuum** [comment]
The `sdl3` branch does not compile anymore because `SDL_SetWindowGrab` has been removed, replaced by other APIs:

https://github.com/libsdl-org/SDL/issues/9339

**Comment by atsb** [comment]
Thanks for bringing it to my attention!

**Comment by Wolf3s** [comment]
> Thanks for bringing it to my attention!

No probs still mantaining.

**Comment by atsb** [comment]
Since SDL3 is now in preview state, I will probably merge this into master soon once I've done some testing and do another official release which will fully deprecate SDL2 support.

**Pull request merged**
