### PR TITLE
Read episodes from mapinfo

### PR DESCRIPTION
**Pull request by azamorapl**
Had to move M_Init after P_Init so that menus are initialized after parsing the lumps

Usage example is inside the explus pwad, adding an episode with the lost levels.

If no episodes are defined, it will skip to the skill menu and default to map 1

### CODE REVIEW

**Comment by atsb** [comment]
Awesome!  I’ll give it a test and merge it after.  Thanks!

**Comment by Wolf3s** [comment]
> Awesome! I’ll give it a test and merge it after. Thanks!

I tested here and it sounds it's not working for me.

**Comment by atsb** [comment]
Works here
sshot022

**Comment by Wolf3s** [comment]
> Works here sshot022

Nice!!!

**Pull request merged**
