### PR TITLE
Cleanup the directory system

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Review by atsb — APPROVED** [review]

**Comment by thekovic** [comment]
How does this change affect Windows?

**Comment by Wolf3s** [comment]
> How does this change affect Windows?

Well it will be more compatible to the Linux because it's literally the same function Used on I_GetBaseDir();

**Comment by atsb** [comment]
> How does this change affect Windows?

Yep for Windows it does not affect anything.  Saves it into the current DIR, it is just that for Linux, Kaiser (for some unfathomable reason) decided to save games into 3 subdirectories on Linux, this cleans it up for those users.

FHS rules aren't always correct.  Some of them are just archaic daft things that should be changed.

**Comment by wolfysdl** [comment]
> > How does this change affect Windows?
> 
> Yep for Windows it does not affect anything. Saves it into the current DIR, it is just that for Linux, Kaiser (for some unfathomable reason) decided to save games into 3 subdirectories on Linux, this cleans it up for those users.
> 
> FHS rules aren't always correct. Some of them are just archaic daft things that should be changed.

Yes that should be clean also.

**Comment by KAMiKAZOW** [comment]
> Saves it into the current DIR, it is just that for Linux, Kaiser (for some unfathomable reason) decided to save games into 3 subdirectories on Linux, this cleans it up for those users.
> 
> FHS rules aren't always correct. Some of them are just archaic daft things that should be changed.

Wait, so it's supposed to be a good change that this engine cannot be packaged as regular ...well... package any longer?

**Comment by atsb** [comment]
What I can do is change it for Linux to save it into ~/.doom64explus for example.  At least then it is a system-agnostic location.  Would this work for you?

**Comment by KAMiKAZOW** [comment]
Yes, that would be great. I think on Linux they would belong into ~/.local/share/doom64explus but Windows also has that "Saved Games" folder.

My suggestion would be to make the default a compile-time option because there is certainly a use case for portable versions even under Linux (never bundled an AppImage myself but I imagine that how it would work there) but also to support GZDoom's "-savedir" and "-config" command line parameters.

So compiling without additional parameters would save the states into the current directory and with some compilation flag into a user directory's subfolder and then users could pick use "-savedir" and "-config" for diverging options at runtime. I actually do this to store GZDoom saves in a cloud-synced folder.

**Comment by Wolf3s** [comment]
> Yes, that would be great. I think on Linux they would belong into ~/.local/share/doom64explus but Windows also has that "Saved Games" folder.
> 
> My suggestion would be to make the default a compile-time option because there is certainly a use case for portable versions even under Linux (never bundled an AppImage myself but I imagine that how it would work there) but also to support GZDoom's "-savedir" and "-config" command line parameters.
> 
> So compiling without additional parameters would save the states into the current directory and with some compilation flag into a user directory's subfolder and then users could pick use "-savedir" and "-config" for diverging options at runtime. I actually do this to store GZDoom saves in a cloud-synced folder.

Sounds nice.

**Comment by Wolf3s** [comment]
> > Yes, that would be great. I think on Linux they would belong into ~/.local/share/doom64explus but Windows also has that "Saved Games" folder.
> > My suggestion would be to make the default a compile-time option because there is certainly a use case for portable versions even under Linux (never bundled an AppImage myself but I imagine that how it would work there) but also to support GZDoom's "-savedir" and "-config" command line parameters.
> > So compiling without additional parameters would save the states into the current directory and with some compilation flag into a user directory's subfolder and then users could pick use "-savedir" and "-config" for diverging options at runtime. I actually do this to store GZDoom saves in a cloud-synced folder.
> 
> Sounds nice.

Some refrence here: https://github.com/ZDoom/gzdoom/blob/303e751a810318f7f4d0b4fbef36d73cf7b104de/src/common/menu/savegamemanager.cpp#L550

**Comment by atsb** [comment]
I've done a basic implementation here.  I'll test it later on my Linux machine:
https://github.com/atsb/Doom64EX-Plus/commit/41006f4ffbdf5ec3137dbacc9b5f954aac7acd8a

Right now, it would just blank-save the files in HOME.  I haven't decided on a '.' location but I guess the executable name makes sense, if we all agree, then I'll just hardcode /.doom64explus onto the end of HOME.

**Pull request merged**
