### PR TITLE
Add support for shader compiler and Some changes.

### PR DESCRIPTION
**Pull request by Wolf3s**
* Added shaders compiler
## Works but the shader doesn't load somehow

### CODE REVIEW

**Comment by atsb** [comment]
Just seen this :) it looks pretty nice for a WIP PR.

I've just done a commit to force a 2.1 GL renderer, however, I'll be happy to resolve and merge this after its finished and we give it a good test.

**Comment by Wolf3s** [comment]
> Just seen this :) it looks pretty nice for a WIP PR.
> 
> I've just done a commit to force a 2.1 GL renderer, however, I'll be happy to resolve and merge this after its finished and we give it a good test.

Yes, but i can add first at least some fragments or Remove all unecessary SDL_GL stuff.

**Comment by atsb** [comment]
> > Just seen this :) it looks pretty nice for a WIP PR.
> > I've just done a commit to force a 2.1 GL renderer, however, I'll be happy to resolve and merge this after its finished and we give it a good test.
> 
> Yes, but i can add first at least some fragments or Remove all unecessary SDL_GL stuff.

Go wild!

**Comment by Wolf3s** [comment]
This should be merged after the all hotfixes releases are finished

**Comment by atsb** [comment]
I can say that the hotfixes are now all done.  Next release is 3.6.6

**Comment by atsb** [comment]
It looks good, though only thing I would add would be to reconcile it against latest master as I’ve removed glew to reduce dependencies.  It was only used for vsync so it wasn’t really justified.  This way we only have SDL2 as a DLL on windows.

**Comment by Wolf3s** [comment]
> It looks good, though only thing I would add would be to reconcile it against latest master as I’ve removed glew to reduce dependencies. It was only used for vsync so it wasn’t really justified. This way we only have SDL2 as a DLL on windows.

I removed GLEXT and i added glew instead

**Comment by atsb** [comment]
Merged

**Pull request merged**
