### PR TITLE
Initial xbox solution support(WIP)

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by atsb** [comment]
Look promising!  It'll be amazing to see if running on an OG Xbox.  I'll keep the branch here until after Christmas so it can be worked on before pushing it to main.

**Comment by Wolf3s** [comment]
> Look promising! It'll be amazing to see if running on an OG Xbox. I'll keep the branch here until after Christmas so it can be worked on before pushing it to main.

I was almost finishing however the vs2003 compiler sucks.

**Comment by atsb** [comment]
Yeah, it is a real shame MS don’t update it or just give it away for folks to home brew with it

**Comment by Wolf3s** [comment]
> Yeah, it is a real shame MS don’t update it or just give it away for folks to home brew with it

In Real microsoft never wanted the c support since Visual c++ was meant to be c++ not c

**Comment by atsb** [comment]
I'll merge this too once the conflicts are done

**Comment by Wolf3s** [comment]
> I'll merge this too once the conflicts are done

Not yet...

**Comment by Wolf3s** [comment]
Fixed the build however it does not work properly tough

**Comment by Wolf3s** [comment]
Closed since i merged this in my workstation branch

**Pull request closed without merging**
