### PR TITLE
v3.6.6(Dev)

### PR DESCRIPTION
**Pull request by Wolf3s**
This branch now turned into a real pr however is mergebale, since the linux now builds.

### CODE REVIEW

**Comment by atsb** [comment]
Woooooo!  I’ll give this a test later today and merge if it’s all good.  Then I’ll focus on that load leaf stuff.

**Comment by atsb** [comment]
I would say, remove the wadgen utility.  I don't support it and will never support users who use it.  I don't want to give the impression that EX+ uses it, so it should be removed.

**Comment by Wolf3s** [comment]
> I would say, remove the wadgen utility. I don't support it and will never support users who use it. I don't want to give the impression that EX+ uses it, so it should be removed.

Ok, the rest i will keep

**Comment by Wolf3s** [comment]
Otherwise do you thinked about to support .n64 files?

**Comment by atsb** [comment]
> Otherwise do you thinked about to support .n64 files?

Never, users can pay for Doom64 instead of the majority most likely downloading and ripping the rom because it is free.

**Comment by atsb** [comment]
SDL Game Controller doesn't work.  Not via windows or steam on a PS4 controller.

**Comment by Wolf3s** [comment]
> > Otherwise do you thinked about to support .n64 files?
> 
> Never, users can pay for Doom64 instead of the majority most likely downloading and ripping the rom because it is free.

Sure thing since there's no way the the game could interpret the n64 file into a wad(it could be cool tough but sucks at little).

**Comment by Wolf3s** [comment]
> 

In Real works however when you don't plug the controller itself it crashes + when you play the controller moves weirdoly.

**Comment by Wolf3s** [comment]
So yeah i deactivated at the moment because all of these problems

**Comment by Wolf3s** [comment]
> So yeah i deactivated at the moment because all of these problems

The tools used on Doom64EX Were updated to support windows and possibly linux

**Comment by atsb** [comment]
I’ve been thinking a lot about this.  I love what you’ve done and I want us to go forward.  I think what is best is this:

Stable branch - will be renamed Unix and will be for non Windows systems.  Will backport changes when or if needed.

This branch - will be pushed to a branch named Windows.  

I will have Main branch detail these things so people who wish to checkout can do so on the right branch.

But due to the user base, Windows will take priority as Unix stuff is pretty stable on that branch anyway.

**Review by atsb — APPROVED** [review]

**Comment by Wolf3s** [comment]
> I’ve been thinking a lot about this. I love what you’ve done and I want us to go forward. I think what is best is this:
> 
> Stable branch - will be renamed Unix and will be for non Windows systems. Will backport changes when or if needed.
> 
> This branch - will be pushed to a branch named Windows.
> 
> I will have Main branch detail these things so people who wish to checkout can do so on the right branch.
> 
> But due to the user base, Windows will take priority as Unix stuff is pretty stable on that branch anyway.

Kind of since this branch is still crashing

**Comment by Wolf3s** [comment]
Suspending the request 👍

**Pull request closed without merging**
