### PR TITLE
Add glfw + a wrapper

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Review by atsb — APPROVED** [review]

**Comment by atsb** [comment]
GLFW is an awesome way to go!

**Comment by atsb** [comment]
When it’s ready it’ll go in

**Comment by Wolf3s** [comment]
> When it’s ready it’ll go in

It's ready however i tried to test on windows and for me atm is not opening nothing.

**Comment by Wolf3s** [comment]
I even tried with the hotfixes

**Comment by atsb** [comment]
Could be something with how the gl_textures.c code is doing things.  It is setting up everything and perhaps the shaders are causing this to crash the texture loading?

**Comment by Wolf3s** [comment]
> 

Looks like is none if these things

**Comment by Wolf3s** [comment]
> > 
> 
> Looks like is none if these things

I will try to remove this gl_utils with something

**Comment by atsb** [comment]
It’s probably something minor, but I’ve never used it before

**Comment by Wolf3s** [comment]
> It’s probably something minor, but I’ve never used it before

same.

**Comment by atsb** [comment]
I guess it helps that I'm not constantly pushing into main now.  You're stabilised and I'm stabilised :D

**Comment by Wolf3s** [comment]
> I guess it helps that I'm not constantly pushing into main now. You're stabilised and I'm stabilised :D

Yes, and that´s why i´m moving all my stable and useful changes into my branch

**Comment by atsb** [comment]
I really can't wait to see what you make of it.  Its good that another release won't be soon, but I'm sure it'll be the best version yet!  Whenever we are done..

**Comment by Wolf3s** [comment]
> I really can't wait to see what you make of it. Its good that another release won't be soon, but I'm sure it'll be the best version yet! Whenever we are done..

Yes, but before the release we should check also the SDL_GameController from vita, it should replace with the xinput.

**Comment by atsb** [comment]
Absolutely!  We definitely need to check literally everything, probably a few months testing at least.

**Pull request closed without merging**
